services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    networks:
      - zabbix-network
    
  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: "mysql"
      ZBX_LISTENIP: "172.30.0.10"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "zabbix"
      MYSQL_ROOT_PASSWORD: "root"
      ZBX_DB_ENCRYPTION: "true" 
    ports:
      - 10051:10051
      - 10050:10050
    depends_on:
      - mysql
    networks:
      zabbix-network:
        ipv4_address: "172.30.0.10"
      
  zabbix-front-end:
    image: zabbix/zabbix-web-nginx-mysql
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      DB_SERVER_HOST: "mysql"
      DB_SERVER_PORT: 3306
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "password"
      PHP_TZ: "America/Sao_Paulo"
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - zabbix-server
    networks:
      - zabbix-network
    
  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: zabbix-agent
    hostname: zabbix-agent
    environment:
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_HOSTNAME: "zabbix-agent"
    depends_on:
      - zabbix-server
      # - mysql
    networks:
      zabbix-network:
        ipv4_address: "172.30.0.11"

    ports:
      - 10051
      - 10050

networks:
  zabbix-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.30.0.0/24
        gateway: 172.30.0.1
  host:
    external: true